"""
Django settings for panopticon project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ
import json
from panopticon.config.webrtc.servers import STUNServer, TURNServer

env = environ.Env()
BASE_DIR = Path(__file__).resolve().parent.parent

env.read_env(BASE_DIR / '.env')

STREAM_SERVICE__INTERNAL_URL = env("STREAM_SERVICE__INTERNAL_URL")

STUN_SERVERS = [
    STUNServer(**server)
    for server in json.loads(env("STUN_SERVERS", default="[]"))
]
TURN_SERVERS = [
    TURNServer(**server) 
    for server in json.loads(env("TURN_SERVERS", default="[]"))
]


DATABASE__DB = env('DATABASE__DB')
DATABASE__USER = env('DATABASE__USER')
DATABASE__PASSWORD = env('DATABASE__PASSWORD')
DATABASE__HOST = env('DATABASE__HOST')
DATABASE__PORT = env('DATABASE__PORT')


STREAM_AUTH__SECRET_KEY = env('STREAM_AUTH__SECRET_KEY')
PANOPTICON_NAMESPACE_UUID = env('PANOPTICON_NAMESPACE_UUID')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('PANOPTICON_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '192.168.0.115', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'account.apps.AccountConfig',
    'streaming.apps.StreamingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'panopticon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'panopticon.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DATABASE__DB,
        'USER': DATABASE__USER,
        'PASSWORD': DATABASE__PASSWORD,
        'HOST': DATABASE__HOST,  # имя сервиса в docker-compose
        'PORT': DATABASE__PORT,
        'OPTIONS': {
            'server_side_binding': True,  # для psycopg3
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# AUTH_USER_MODEL = 'account.UUIDUser'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Minsk'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_URL = '/account/login/'
LOGIN_REDIRECT_URL = '/account/profile/'



EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'






# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your_email@gmail.com'  # Твой email
# EMAIL_HOST_PASSWORD = 'your_email_password'  # Пароль приложения
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER