services:
  vstream_scaner:
    container_name: vstream_scaner
    build: ./vstream_scaner
    env_file: .env
    environment:
      - DB_URL=mysql+aiomysql://${DB_USER}:${DB_PASSWORD}@database:3306/${DB_NAME}
      - PYTHONPATH=/
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - ./vstream_scaner/app:/app  # Монтируем код для hot-reload
      
      # - ./alembic:/app/alembic
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    # alembic upgrade head && 

volumes:
  database_data:

networks:
  app_network:
    driver: bridge