name: "calibration_preprocessor"
backend: "python"
max_batch_size: 8  # Позволяет Тритону склеивать до 8 кадров от разных людей в одну пачку

# ВХОДНЫЕ ДАННЫЕ (должны совпадать с именами в твоем model.py)
input [
  {
    name: "session_id"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "frame_data"
    data_type: TYPE_UINT8
    dims: [ -1 ] # Плоский массив байт (raw bytes из твоего proto)
  },
  {
    name: "width"
    data_type: TYPE_INT32
    dims: [ 1 ]
  },
  {
    name: "height"
    data_type: TYPE_INT32
    dims: [ 1 ]
  },
  {
    name: "channels"
    data_type: TYPE_INT32
    dims: [ 1 ]
  },
  {
    name: "ts"
    data_type: TYPE_INT64
    dims: [ 1 ]
  }
]

# ВЫХОДНЫЕ ДАННЫЕ
output [
  {
    name: "session_id"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "comment"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "ts"
    data_type: TYPE_INT64
    dims: [ 1 ]
  },
  {
    name: "boxes"
    data_type: TYPE_INT32
    dims: [ -1, 4 ] # Список BoundingBox. -1 значит "любое количество найденных лиц"
  }
]


instance_group [
  {
    count: 1          # Сколько копий модели запустить (для CPU 1-2 обычно за глаза)
    kind: KIND_CPU
  }
]

# ОПТИМИЗАЦИЯ РЕАЛТАЙМА
dynamic_batching {
  max_queue_delay_microseconds: 5000 # Ждать 5мс, чтобы добрать кадры от других сессий
}