# Generated by Django 6.0.1 on 2026-03-23 00:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('running', 'Running'), ('finished', 'Finished'), ('interrupted', 'Interrupted'), ('failed', 'Failed')], default='started', max_length=20)),
            ],
            options={
                'db_table': 'session',
                'managed': True,
                'indexes': [models.Index(fields=['status'], name='session_status_dd82f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='StreamingVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=500)),
                ('s3_bucket', models.CharField(max_length=255)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='streaming.streamingsession')),
            ],
            options={
                'db_table': 'video',
                'managed': True,
                'indexes': [models.Index(fields=['s3_key'], name='video_s3_key_909dcb_idx'), models.Index(fields=['session_id'], name='video_session_2df6e4_idx')],
            },
        ),
    ]
