# Generated by Django 6.0.1 on 2026-03-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamingvideo',
            name='s3_bucket',
        ),
        migrations.AddField(
            model_name='streamingvideo',
            name='fps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamingvideo',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamingvideo',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='streamingvideo',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
