# Generated by Django 5.1.5 on 2025-10-30 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('test_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('running', 'Running'), ('finished', 'Finished'), ('interrupted', 'Interrupted'), ('failed', 'Failed')], default='started', max_length=20)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('incidents', models.JSONField(blank=True, null=True)),
                ('ml_metrics', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_session',
                'indexes': [models.Index(fields=['user_id'], name='app_session_user_id_40fd68_idx'), models.Index(fields=['status'], name='app_session_status_c5ab52_idx')],
            },
        ),
    ]
