# Generated by Django 5.1.5 on 2025-10-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='TestingSession',
        ),
        migrations.RenameIndex(
            model_name='testingsession',
            new_name='testing_ses_user_id_fda651_idx',
            old_name='app_session_user_id_40fd68_idx',
        ),
        migrations.RenameIndex(
            model_name='testingsession',
            new_name='testing_ses_status_6a7c9f_idx',
            old_name='app_session_status_c5ab52_idx',
        ),
        migrations.AlterModelTable(
            name='testingsession',
            table='testing_session',
        ),
    ]
