name: "monitoring_pipeline"
platform: "ensemble"
max_batch_size: 8


input [
  {
    name: "session_id_input"    # Название входа ансамбля
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "frame_data_input"
    data_type: TYPE_UINT8
    dims: [-1]
  },
  {
    name: "width_input"
    data_type: TYPE_INT32
    dims: [1]
  },
  {
    name: "height_input"
    data_type: TYPE_INT32
    dims: [1]
  },
  {
    name: "channels_input"
    data_type: TYPE_INT32
    dims: [1]
  },
  {
    name: "ts_input"
    data_type: TYPE_INT64
    dims: [1]
  }
]

output [
  {
    name: "session_id_output"   # Название выхода ансамбля
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "comment_output"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "ts_output"
    data_type: TYPE_INT64
    dims: [1]
  },
  {
    name: "boxes_output"
    data_type: TYPE_INT32
    dims: [-1, 4]
  }
]


ensemble_scheduling {
  step [
    {
      model_name: "monitoring_preprocessor"
      model_version: -1
      input_map {
        key: "session_id"     # Имя входа в модели
        value: "session_id_input"  # Имя входа в ансамбле
      }
      input_map {
        key: "frame_data"
        value: "frame_data_input"
      }
      input_map {
        key: "width"
        value: "width_input"
      }
      input_map {
        key: "height"
        value: "height_input"
      }
      input_map {
        key: "channels"
        value: "channels_input"
      }
      input_map {
        key: "ts"
        value: "ts_input"
      }

      output_map {
        key: "session_id"
        value: "preproc_session_id"
      }
      output_map {
        key: "comment"
        value: "preproc_comment"
      }
      output_map {
        key: "ts"
        value: "preproc_ts"
      }
      output_map {
        key: "boxes"
        value: "preproc_boxes"
      }
    },
    {
      model_name: "monitoring_postprocessor"
      model_version: -1
      input_map {
        key: "session_id"
        value: "preproc_session_id"
      }
      input_map {
        key: "comment"
        value: "preproc_comment"
      }
      input_map {
        key: "ts"
        value: "preproc_ts"
      }
      input_map {
        key: "boxes"
        value: "preproc_boxes"
      }


      output_map {
        key: "session_id"
        value: "session_id_output"
      }
      output_map {
        key: "comment"
        value: "comment_output"
      }
      output_map {
        key: "ts"
        value: "ts_output"
      }
      output_map {
        key: "boxes"
        value: "boxes_output"
      }
    }
  ]
}